image: python:buster

include:
  - template: Dependency-Scanning.gitlab-ci.yml


test:
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install -r requirements-docs.txt
    - sphinx-build -b html . public
  only:
  - branches
  except:
  - master

pages:
  stage: deploy
  script:
    - pip install -r requirements.txt
    - pip install -r requirements-docs.txt
    - sphinx-build -b html . public
    - python utils/dry_run.py
  artifacts:
    paths:
    - public
  only:
  - master
