image: python:buster

test:
  stage: test
  script:
    - apt install gcc
    - pip install -r requirements.txt
    - pip install -r requirements-docs.txt
    - sphinx-build -b html . public
  only:
  - branches
  except:
  - master

pages:
  stage: deploy
  script:
    - apt install gcc
    - pip install -r requirements.txt
    - pip install -r requirements-docs.txt
    - sphinx-build -b html . public
  artifacts:
    paths:
    - public
  only:
  - master
