# This is a basic workflow to help you get started with Actions

name: Docker

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
    paths:
      - '**.py'
      - 'requirements*.txt'
      - '.github/workflows/docker.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: octo-tg-bot/octotgbot
          username: ${{ github.repository_owner }}
          password: ${{ secrets.USER_GH_TOKEN }}
          registry: ghcr.io
          buildargs: CI,GITHUB_SHA,GITHUB_RUN_NUMBER,GITHUB_REF